version: '2.0'
services:
  mongodb:
    build: ./mongodb
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 27017:27017
  quill:
    build: ./app
    depends_on:
      - mongodb
    volumes:
      - ./app:/quill/
      - /quill/node_modules
    ports:
      - 3001:3001
    command: npx mocha --exit
